/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BUS.LichChieuBUS;
import DTO.LichChieuDTO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Zed
 */
public class QuanLiLichChieu extends javax.swing.JFrame {

    public ArrayList<LichChieuDTO> dslc;
    public static LichChieuDTO baseLC = new LichChieuDTO();
    
    /**
     * Creates new form QuanLiLichChieu
     */
    public QuanLiLichChieu() {
        
        initComponents();
        loadDataTable();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lableQLLC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lableDSLC = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonTimKiem = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableQLLC = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        dateSearch = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbBuoiChieu = new javax.swing.JComboBox<>();
        buttonThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Lịch Chiếu");

        jPanel1.setBackground(new java.awt.Color(194, 54, 22));

        lableQLLC.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lableQLLC.setForeground(new java.awt.Color(255, 255, 255));
        lableQLLC.setText("Quản Lý Lịch Chiếu Phim");

        lableDSLC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lableDSLC.setText("Danh Sách Lịch Chiếu");

        buttonTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        buttonTimKiem.setText("Tìm");
        buttonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimKiemActionPerformed(evt);
            }
        });

        buttonAdd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        buttonAdd.setText("Thêm");
        buttonAdd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonAddStateChanged(evt);
            }
        });
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddMouseClicked(evt);
            }
        });
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonDelete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        buttonDelete.setText("Xóa");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonUpdate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        buttonUpdate.setText("Sửa");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        tableQLLC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tableQLLC.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tableQLLC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableQLLC.setGridColor(new java.awt.Color(0, 0, 0));
        tableQLLC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQLLCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableQLLC);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dateSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tìm ngày chiếu");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Chọn buổi chiếu");

        cbBuoiChieu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbBuoiChieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sáng", "Trưa", "Chiều", "Tối" }));
        cbBuoiChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuoiChieuActionPerformed(evt);
            }
        });

        buttonThoat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        buttonThoat.setText("Thoát");
        buttonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lableDSLC)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbBuoiChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(buttonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dateSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(buttonThoat)
                        .addGap(23, 23, 23))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lableDSLC)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(dateSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuoiChieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTimKiem)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonAdd)
                    .addComponent(buttonDelete)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonThoat))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lableQLLC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lableQLLC)
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        ThemLichChieu add = new ThemLichChieu();
        add.setVisible(true);
        add.setLocationRelativeTo(null);
        add.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        
        
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_buttonAddMouseClicked

    private void buttonAddStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonAddStateChanged

    }//GEN-LAST:event_buttonAddStateChanged

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
       QuanLyLichChieu_CapNhatLichChieu them = new QuanLyLichChieu_CapNhatLichChieu();
       int row = tableQLLC.getSelectedRow();
       if(row == -1)
       {
       JOptionPane.showMessageDialog(null, "Chưa chọn dòng");
       }
       else
       {
       baseLC.setNgayChieu(tableQLLC.getValueAt(row, 0).toString());
       baseLC.setBuoiChieu(tableQLLC.getValueAt(row, 1).toString());
       baseLC.setMaPhong(tableQLLC.getValueAt(row, 2).toString());
       baseLC.setMaPhim(tableQLLC.getValueAt(row, 3).toString());
       baseLC.setMaLV(tableQLLC.getValueAt(row, 4).toString());
       them.loadData2(baseLC);//load data cua dong hien tai
       them.setVisible(true);
       them.setLocationRelativeTo(null);
       them.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       }
   
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void tableQLLCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableQLLCMouseClicked
      
    }//GEN-LAST:event_tableQLLCMouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
       int row = tableQLLC.getSelectedRow();
       LichChieuBUS lcb = new LichChieuBUS();
       if(row == -1)
       {
       JOptionPane.showMessageDialog(null, "Chưa chọn dòng");
       }
       else
       {
       Object []options = {"Đồng Ý", "Hủy"};
       int n = JOptionPane.showOptionDialog(null, "Bạn có chắc chắn muốn xóa dữ liệu không ?", "Xóa", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
       
       if(n == 0){
       baseLC.setNgayChieu(tableQLLC.getValueAt(row, 0).toString());
       baseLC.setBuoiChieu(tableQLLC.getValueAt(row, 1).toString());
       baseLC.setMaPhong(tableQLLC.getValueAt(row, 2).toString());
       baseLC.setMaPhim(tableQLLC.getValueAt(row, 3).toString());
       baseLC.setMaLV(tableQLLC.getValueAt(row, 4).toString());
       if(lcb.DeleteData(baseLC) == true)
       {
              JOptionPane.showMessageDialog(null, "Xóa thành công");
              this.loadDataTable();
       }
       else
       {
              JOptionPane.showMessageDialog(null, "Xóa không thành công");
       
       }
       }
       }
       
       
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.loadDataTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimKiemActionPerformed
       
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String ngayChieu = sdf.format(dateSearch.getDate());
        String buoiChieu = cbBuoiChieu.getSelectedItem().toString();
        this.loadSearchDataTable(ngayChieu, buoiChieu);
        
        
    }//GEN-LAST:event_buttonTimKiemActionPerformed

    private void cbBuoiChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuoiChieuActionPerformed
       
    }//GEN-LAST:event_cbBuoiChieuActionPerformed

    private void buttonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonThoatActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonThoat;
    private javax.swing.JButton buttonTimKiem;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox<String> cbBuoiChieu;
    private com.toedter.calendar.JDateChooser dateSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lableDSLC;
    private javax.swing.JLabel lableQLLC;
    private javax.swing.JTable tableQLLC;
    // End of variables declaration//GEN-END:variables
//load data từ database lên bảng
public void loadDataTable()
{
       tableQLLC.removeAll();
       DefaultTableModel model =  (DefaultTableModel)tableQLLC.getModel();
       dateSearch.setCalendar(Calendar.getInstance()); //Sét ngày trong Jdatechooser = ngày hiện tại.
       String []colsName = {"Ngày Chiếu", "Buổi Chiếu", "Mã Phòng","Mã Phim", "Mã Loại Vé"};
       model.setColumnIdentifiers(colsName);
       tableQLLC.setModel(model); 
       model.setRowCount(0);
       dslc = new LichChieuBUS().getDanhSachLichChieu();
        for(LichChieuDTO lct :dslc)
        {
            
            String row[];
            row = new String[5];
            row[0] = lct.getNgayChieu();
            row[1] = lct.getBuoiChieu();
            row[2] = lct.getMaPhong();
            row[3] = lct.getMaPhim();
            row[4] = lct.getMaLV();
           
            model.addRow(row);
        }
        
}

//Load lại dữ liệu sau khi tìm kiếm.
public void loadSearchDataTable(String ngayChieu, String buoiChieu)
{
   tableQLLC.removeAll();
   DefaultTableModel model =  (DefaultTableModel)tableQLLC.getModel();
   
   String []colsName = {"Ngày Chiếu", "Buổi Chiếu", "Mã Phòng","Mã Phim", "Mã Loại Vé"};
       model.setColumnIdentifiers(colsName);
       tableQLLC.setModel(model); 
       model.setRowCount(0);
       dslc = new LichChieuBUS().searchDanhSachLichChieu(ngayChieu, buoiChieu);
        for(LichChieuDTO lct :dslc)
        {
            
            String row[];
            row = new String[5];
            row[0] = lct.getNgayChieu();
            row[1] = lct.getBuoiChieu();
            row[2] = lct.getMaPhong();
            row[3] = lct.getMaPhim();
            row[4] = lct.getMaLV();
           
            model.addRow(row);
        }
        
}



}



