/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author phannhan
 */
public class QuanLyPhongChieu_ThemPhongChieu extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyPhongChieu_ThemPhongChieu
     */
    public QuanLyPhongChieu_ThemPhongChieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelThemphongchieu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelMaphong = new javax.swing.JLabel();
        labelTenphong = new javax.swing.JLabel();
        labelKichthuoc = new javax.swing.JLabel();
        labelSoluongghe = new javax.swing.JLabel();
        labelMaychieu = new javax.swing.JLabel();
        labelAmthanh = new javax.swing.JLabel();
        textfieldMaphong = new javax.swing.JTextField();
        textfieldTenphong = new javax.swing.JTextField();
        textfieldKichthuoc = new javax.swing.JTextField();
        textfieldSoluongghe = new javax.swing.JTextField();
        textfieldMaychieu = new javax.swing.JTextField();
        textfieldAmthanh = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        labelXacnhanthemphongchieumoi = new javax.swing.JLabel();
        buttonThem = new javax.swing.JButton();
        buttonHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(194, 54, 22));

        labelThemphongchieu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelThemphongchieu.setText("Thêm phòng chiếu ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelThemphongchieu, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelThemphongchieu, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        labelMaphong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelMaphong.setText("Mã phòng");

        labelTenphong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelTenphong.setText("Tên phòng");

        labelKichthuoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelKichthuoc.setText("Kích thước ");

        labelSoluongghe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelSoluongghe.setText("Số lượng ghế ");

        labelMaychieu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelMaychieu.setText("Máy chiếu ");

        labelAmthanh.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelAmthanh.setText("Âm thanh ");

        textfieldMaphong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textfieldMaphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldMaphongActionPerformed(evt);
            }
        });

        textfieldTenphong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textfieldTenphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldTenphongActionPerformed(evt);
            }
        });

        textfieldKichthuoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        textfieldSoluongghe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textfieldSoluongghe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldSoluonggheActionPerformed(evt);
            }
        });

        textfieldMaychieu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        textfieldAmthanh.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textfieldAmthanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldAmthanhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMaphong)
                    .addComponent(labelTenphong)
                    .addComponent(labelKichthuoc)
                    .addComponent(labelSoluongghe)
                    .addComponent(labelMaychieu)
                    .addComponent(labelAmthanh))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textfieldMaphong)
                    .addComponent(textfieldTenphong)
                    .addComponent(textfieldKichthuoc)
                    .addComponent(textfieldSoluongghe)
                    .addComponent(textfieldMaychieu, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(textfieldAmthanh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaphong)
                    .addComponent(textfieldMaphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTenphong)
                    .addComponent(textfieldTenphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldKichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSoluongghe)
                    .addComponent(textfieldSoluongghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaychieu)
                    .addComponent(textfieldMaychieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAmthanh)
                    .addComponent(textfieldAmthanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelXacnhanthemphongchieumoi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelXacnhanthemphongchieumoi.setText("Xác nhận thêm phòng chiếu mới ");

        buttonThem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonThem.setText("Thêm");

        buttonHuy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonHuy.setText("Huỷ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonThem)
                        .addGap(88, 88, 88)
                        .addComponent(buttonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelXacnhanthemphongchieumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelXacnhanthemphongchieumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonThem)
                    .addComponent(buttonHuy))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldTenphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldTenphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldTenphongActionPerformed

    private void textfieldAmthanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldAmthanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldAmthanhActionPerformed

    private void textfieldSoluonggheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldSoluonggheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldSoluonggheActionPerformed

    private void textfieldMaphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldMaphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldMaphongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongChieu_ThemPhongChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongChieu_ThemPhongChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongChieu_ThemPhongChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongChieu_ThemPhongChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhongChieu_ThemPhongChieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHuy;
    private javax.swing.JButton buttonThem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAmthanh;
    private javax.swing.JLabel labelKichthuoc;
    private javax.swing.JLabel labelMaphong;
    private javax.swing.JLabel labelMaychieu;
    private javax.swing.JLabel labelSoluongghe;
    private javax.swing.JLabel labelTenphong;
    private javax.swing.JLabel labelThemphongchieu;
    private javax.swing.JLabel labelXacnhanthemphongchieumoi;
    private javax.swing.JTextField textfieldAmthanh;
    private javax.swing.JTextField textfieldKichthuoc;
    private javax.swing.JTextField textfieldMaphong;
    private javax.swing.JTextField textfieldMaychieu;
    private javax.swing.JTextField textfieldSoluongghe;
    private javax.swing.JTextField textfieldTenphong;
    // End of variables declaration//GEN-END:variables
}
